<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="tool-shortcuts">
      <text>Tool Shortcuts</text>
        <Action name="KisToolSelectContiguous">
      <icon>tool_contiguous_selection</icon>
      <text>Magic Wand</text>
      <whatsThis></whatsThis>
      <toolTip>Magic Wand </toolTip>
      <iconText>Magic Wand</iconText>
      <shortcut>W</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
